version: '3'
services:
  multi-tier-db:
    image: bharathsharath/db
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  multi-tier-mem:
    image: memcached
    ports:
      - "11211:11211"

  multi-tier-rmq:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  multi-tier-app:
    image: bharathsharath/app
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  multi-tier-web:
    image: bharathsharath/web
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
